In [3]:
# numpy is a library that allows for the use of arrays and matrices in python
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [5]:
type(a)

numpy.ndarray

- Basic Operation of array

In [6]:
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [7]:
# creating a 2D array
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [8]:
# creating a 3D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


- Methods

In [9]:
print(b.shape) #(2,2,2) 2 arrays , 2 rows, 2 columns

(2, 2, 2)


In [10]:
print(a.ndim)

2


In [11]:
print(a.dtype)

int64


In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [14]:
np.random.randint(10,30, size=(3,3))

array([[19, 24, 26],
       [29, 26, 19],
       [23, 10, 23]], dtype=int32)

In [15]:
x = np.array([[7,2,3],
              [2,5,2,],
              [3,5,1]])

y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])

print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [16]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [17]:
print(x.dot(y)) # matrix multiplication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [18]:
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [19]:
x.prod() # it gives multiplication of all the elements of the array

np.int64(12600)

In [20]:
x.mean() # it gives the mean of all the elements of the array

np.float64(3.3333333333333335)

In [21]:
x.mean(axis=0) # it gives the mean of each columns

array([4., 4., 2.])

In [22]:
x.mean(axis=1) #it gives the mean of each row

array([4., 3., 3.])

In [23]:
print(x.sum()) # it gives the sum of all the elements of the array
print(x.var()) # it gives the  variance of the all elements of the aaray
print(x.std()) # it gives the  standard deviation of all the elements of the array

30
3.3333333333333335
1.8257418583505538


In [24]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 25)) # it gives the 25th percentile of the array
print(np.percentile(a, 50)) # it gives the 50th percentile of the array
print(np.percentile(a, 75)) # it gives the 75th percentile of the array

3.0
5.0
7.0


In [25]:
arr = np.random.randint(10,50, size=(4,4))
print(arr)

[[45 20 41 25]
 [28 13 43 22]
 [33 44 49 29]
 [32 45 18 18]]


In [26]:
print('8*2')
print(arr.reshape(8,2))

8*2
[[45 20]
 [41 25]
 [28 13]
 [43 22]
 [33 44]
 [49 29]
 [32 45]
 [18 18]]


In [27]:
print('2*8')
print(arr.reshape(2,8))

2*8
[[45 20 41 25 28 13 43 22]
 [33 44 49 29 32 45 18 18]]


In [28]:
print(x[0])
print(x[0,0])

[7 2 3]
7


In [29]:
print(x[:3])
print(x[2:])

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[3 5 1]]
